modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/yori3o/Yori3osGrapplingHooks/issues"
license = "MIT License"

[[mods]]
modId = "yo_hooks"
version = "${version}"
displayName = "Yori3o's Grappling Hooks"
authors = "Yori3o"
description = '''
Adds grappling hooks to the game.
'''
logoFile = "logo.png"
displayURL="https://modrinth.com/mod/yori3os-grappling-hooks"

[[dependencies.yo_hooks]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yo_hooks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yo_hooks]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "yo_hooks.mixins.json"
